# Generated by Django 4.1 on 2023-01-17 03:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_alter_swellbuoy_current_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='surfsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='surfspot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='swell_buoy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.swellbuoy'),
        ),
        migrations.AlterField(
            model_name='surfspot',
            name='tide_buoy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.tidebuoy'),
        ),
    ]
