# Generated by Django 4.1 on 2023-01-17 03:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0004_surfsession_user_surfspot_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfspot',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surf_spots', to=settings.AUTH_USER_MODEL),
        ),
    ]
