# Generated by Django 4.1 on 2023-01-19 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_swelldatapoint_surf_session_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='swellbuoy',
            name='previous_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.swelldatapoint'),
        ),
        migrations.AddField(
            model_name='tidebuoy',
            name='previous_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.tidedatapoint'),
        ),
        migrations.AlterField(
            model_name='swellbuoy',
            name='current_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.swelldatapoint'),
        ),
        migrations.AlterField(
            model_name='tidebuoy',
            name='current_data',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='api.tidedatapoint'),
        ),
    ]
