# Generated by Django 4.1 on 2023-01-16 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tidedatapoint',
            name='surf_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.surfsession'),
        ),
    ]
