# Generated by Django 4.1 on 2023-01-19 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_surfspot_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfsession',
            name='surf_spot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surf_sessions', to='api.surfspot'),
        ),
    ]
