# Generated by Django 4.1 on 2023-01-19 17:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_surfsession_surf_spot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='swelldatapoint',
            name='surf_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='swell_data', to='api.surfsession'),
        ),
        migrations.AlterField(
            model_name='tidedatapoint',
            name='surf_session',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tide_data', to='api.surfsession'),
        ),
    ]
