# Generated by Django 4.1 on 2023-01-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_swellbuoy_previous_data_tidebuoy_previous_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='latitude',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
        migrations.AlterField(
            model_name='marker',
            name='longitude',
            field=models.DecimalField(decimal_places=10, max_digits=30),
        ),
    ]
