# Generated by Django 4.1 on 2023-02-01 21:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0009_alter_marker_latitude_alter_marker_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surfsession',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='surf_sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
